#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RandomPasswordGenerator.Resource", IsApplication=true)]

namespace RandomPasswordGenerator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primary_dark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_content_copy_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_content_copy_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_favorite_border_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_favorite_border_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_favorite_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int applicationName = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int application_name_input = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int btnCopy = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int btnGenerate = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int btnSave = 2131230728;
			
			// aapt resource value: 0x7f080019
			public const int digitsCheckbox = 2131230745;
			
			// aapt resource value: 0x7f080017
			public const int digitsExample = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int digitsText = 2131230744;
			
			// aapt resource value: 0x7f080007
			public const int generatedPassword = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int layoutBody = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int layoutBottom = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int layoutCheckboxes = 2131230735;
			
			// aapt resource value: 0x7f080006
			public const int layoutGeneratePassword = 2131230726;
			
			// aapt resource value: 0x7f08001e
			public const int layoutLength = 2131230750;
			
			// aapt resource value: 0x7f080016
			public const int lowerCaseCheckbox = 2131230742;
			
			// aapt resource value: 0x7f080014
			public const int lowerCaseExample = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int lowerCaseText = 2131230741;
			
			// aapt resource value: 0x7f080024
			public const int menu_about = 2131230756;
			
			// aapt resource value: 0x7f080023
			public const int menu_bookmark = 2131230755;
			
			// aapt resource value: 0x7f080025
			public const int menu_change_log = 2131230757;
			
			// aapt resource value: 0x7f080002
			public const int passwordName = 2131230722;
			
			// aapt resource value: 0x7f08001f
			public const int seekBarLength = 2131230751;
			
			// aapt resource value: 0x7f08000a
			public const int seekBarSentence = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int seekBarValue = 2131230731;
			
			// aapt resource value: 0x7f08001c
			public const int specialCharactersCheckbox = 2131230748;
			
			// aapt resource value: 0x7f08001a
			public const int specialCharactersExample = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int specialCharactersText = 2131230747;
			
			// aapt resource value: 0x7f08001d
			public const int subtitleLength = 2131230749;
			
			// aapt resource value: 0x7f08000e
			public const int subtitleParameters = 2131230734;
			
			// aapt resource value: 0x7f080022
			public const int toolbar = 2131230754;
			
			// aapt resource value: 0x7f080000
			public const int toolbarBookmarks = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int toolbarHome = 2131230725;
			
			// aapt resource value: 0x7f080021
			public const int txtPassword = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int txtSource = 2131230752;
			
			// aapt resource value: 0x7f080013
			public const int upperCaseCheckbox = 2131230739;
			
			// aapt resource value: 0x7f080010
			public const int upperCaseExample = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int upperCaseText = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int view1 = 2131230738;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BookmarksLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_about = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_change_log = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_save = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int listview_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int toolbar = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu_toolbar_home = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int about_text = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int about_title = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int application_name = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int change_log_history_text = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int change_log_history_title = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int change_log_title = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int cl_current_version_text = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int cl_current_version_title = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int save_subtitle = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int save_title = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
